apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vote-deployment
  name: vote-service
  namespace: vote
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 80    
    nodePort: 31000  
  selector:
    app: vote-deployment
  type: NodePort
status:
  loadBalancer: {}