apiVersion: v1
data:
  MYSQL_DATABASE: ZHJ1cGFsLWRhdGFiYXNl
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MYSQL_USER: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: drupal-mysql-secret

YOU MUST GENERATE SECRET WITH THIS CODE: 
kubectl create secret generic drupal-mysql-secret --from-literal=MYSQL_ROOT_PASSWORD=root_password --from-literal=MYSQL_DATABASE=drupal-database --from-literal=MYSQL_USER=root_user
